name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 01 -> Initialize Actions for mamad project
    - uses: actions/checkout@v3
    - name: 02 -> Setup .NET on repository
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: 03 -> Restore dependencies
      run: dotnet restore
    - name: 04 -> Build
      run: dotnet build --no-restore
    - name: 05 -> Test reposirory
      run: dotnet test --no-build --verbosity normal
